services:
  front:
    build: ./front
    volumes:
      - ./front/my-app:/myapp
    ports:
      - 3000:3000
    working_dir: /myapp
    tty: true
  back:
    build: ./back
    volumes:
      - ./back/dockervenv:/src/.venv
      - ./back:/src
    tty: true
    ports:
      - 8000:8000
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "demo"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
volumes:
  mysql_data:
